### ISSUE TITLE
MVVM?

### ISSUE THREAD

**Issue by beavi5** [aleksanderwozniak/deer#26]
Hi, this approach is more like MVVM with "clean".
View, ViewModel(Bloc in u case), Interactors and Repository.

What are the differences?

**Comment by aleksanderwozniak** [comment]
Yeah, this is somewhat correct.
Basically, I wanted to write reactive code with single source of truth - and found BLoC pattern this way. 

As you can see [here](https://flutter.io/docs/development/data-and-backend/state-mgmt/options), there is no 'official' MVC/MVP/MVVM for Flutter - rather setState/ScopedModel/Redux/BLoC. But even though naming is different, key concepts are similar/same, as you already noticed ;)
