### ISSUE TITLE
seedValue parameter isn't define in android studio

### ISSUE THREAD

**Issue by hkelvinc1** [aleksanderwozniak/deer#28]
As the title says.

**Comment by aleksanderwozniak** [comment]
Could you send here your error logs? 
Also, do you have any particular seedValue in mind? There are plenty in this project.

**Comment by lukaspili** [comment]
Probably because RxDart implemented a breaking change in the latest release for BehaviorSubject.
`seedValue` param has been replaced by a named constructor: `BehaviorSubject.seeded()`

**Comment by aleksanderwozniak** [comment]
Should be solved with #31
