### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by sturza** [aleksanderwozniak/deer#33]
Compiler message:
lib/presentation/screen/calendar/calendar_screen.dart:184:7: Error: No named parameter with the name 'onFormatChanged'.
      onFormatChanged: _onCalendarFormatChanged,
      ^^^^^^^^^^^^^^^
file:///Users/bsturza/Desktop/Development/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-1.1.4/lib/table_calendar.dart:127:3: Context: Found this candidate, but the arguments don't match.
  TableCalendar({

**Comment by sturza** [comment]
it cannot find anything in the TableCalendar. If i comment it out, the app builds

**Comment by aleksanderwozniak** [comment]
I assume you are on `master` branch. If you check out to `dev` branch, it should all work correctly.
Just run `git checkout dev` in the project directory.

Right now I am working on a big update - I will merge branches when it is ready.

**Comment by aleksanderwozniak** [comment]
@sturza 
You can now just update from `master`, since #34 fixes all breaking changes.
